run-name: GitHub Actions build-test

on: [push]

jobs:

  build-run:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libnetcdf-pnetcdf-19
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the netcdf code
        run: |
          apt list --manual-installed=true
